---
title: "Title: Better two than one: considering female´s morphology increases the understanding of Anolis diversification"
#Authors: JD Rodríguez-Rodríguez & ML Calderón-Espinosa 
output: html_notebook
---
```{r}
#Clean workspace
rm(list=ls())
#Call packages
library(ape)
library(factoextra)
library(devtools)
library(MVN)
library(mvnormtest)
library(bestNormalize)
library(mnormt)
library(nortest)
library(permute)
library(MASS)
library(tidyverse)
library(klaR)
library(pander)
library(dplyr)
library(ggplot2)
library(grid)
library(gridExtra)
library(vegan)
library(car)
library(geiger)
library(nlme)
library(phytools)
library(maps)
library(phangorn)
library(dplyr)
library(stats)
library(cluster)
```
```{r}
#Pleliminary analysis 
#Database
`0_base_total_rev` <- read.csv("C:/Users/juadr/OneDrive/Escritorio/Documentos trabajo de grado/Anolis_R/0_base_total_rev.csv", sep=";")
data<-`0_base_total_rev`
data<-data[c(-8)]
data<-na.omit(data)
data<- data[!duplicated(data$ICN), ]
data<-textshape::column_to_rownames(data, loc = 1)
#Data subsets
auratus<-subset(data,ESPECIE=="auratus")
auratus<-subset(data,ESPECIE=="auratus")
mariarum<-subset(data,ESPECIE=="fuscoauratus")
mariarum<-subset(data,ESPECIE=="mariarum")
maculiventris<-subset(data,ESPECIE=="maculiventris")
tolimensis<-subset(data,ESPECIE=="tolimensis")
auratus<-subset(data,ESPECIE=="auratus")
notopholis<-subset(data,ESPECIE=="notopholis")
tropidogaster<-subset(data,ESPECIE=="tropidogaster/gaigei")
chloris<-subset(data,ESPECIE=="chloris")
heterodermus<-subset(data,ESPECIE=="heterodermus")
scypheus<-subset(data,ESPECIE=="scypheus")
huilae<-subset(data,ESPECIE=="ventrimaculatus")
huilae<-subset(data,ESPECIE=="huilae")
maculigula<-subset(data,ESPECIE=="maculigula")
apollinaris<-subset(data,ESPECIE=="apollinaris")
#Analysis per species (repeat with every species)  
#antonii
#auratus
#fuscoauratus
#mariarum
#maculiventris
#tolimensis
#notopholis
#tropidogaster
#chloris
#heterodermus
#scypheus
#ventrimaculatus
#huilae
#maculigula
#apollinaris
#transformar datos y corregir por tamaño 
sex = as.factor((species)[,2])
LRC = as.numeric((species)[,6])
LB = as.numeric((species)[,7])
LP = as.numeric((species)[,8])
LT = as.numeric((species)[,9])
ANC = as.numeric((species)[,10])
ALC = as.numeric((species)[,11])
LAC = as.numeric((species)[,12])
NL = as.numeric((species)[,13])
LRCl<-log(LRC)
LBl<-log(LB)
LPl<-log(LP)
LTl<-log(LT)
ANCl<-log(ANC)
ALCl<-log(ALC)
LACl<-log(LAC)
NLl<-log(NL)
regLB = lm(LRCl ~ LBl) 
regLP = lm(LRCl ~ LPl) 
regLT = lm(LRCl ~ LTl) 
regANC = lm(LRCl ~ ANCl) 
regALC = lm(LRCl ~ ALCl) 
regLAC = lm(LRCl ~ LACl) 
regNL = lm(LRCl ~ NLl) 
LBr = regLB$resid
LPr = regLP$resid
LTr = regLT$resid
ANCr = regANC$resid
ALCr = regALC$resid
LACr = regLAC$resid
NLr = regNL$resid
names = row.names(species)
log.species=data.frame(cbind(LRCl, LBr, LPr, LTr, ANCr, ALCr, LACr))
log.species.nl =data.frame(cbind(LPr, LTr, ANCr, NLr))
log.species.f =data.frame(cbind(LPr, LTr, ANCr))
#Test supuestos
table(species$SEXO)#numero de individuos 
#normalidad 
male <-subset(log.species,species$SEXO=="M")
female <-subset(log.species,species$SEXO=="H")
shapiro.test(male$LRCl) #menos de 50 p>0.05 para normalidad 
shapiro.test(female$LRCl)
lillie.test(male$LRCl) #mas de 50 
#lillie.test(female$LRCl)
#homocedasticidad
fligner.test(log.species$LRCl~species$SEXO)#p>0.05 para hpmcedasticidad 
leveneTest(log.species$LRCl~species$SEXO)
#ANOVA~requiere normalidad 
anova<-aov(log.species$LRCl~species$SEXO)
summary.aov(anova)
#WIlcoxon~no requiere normalidad pero requiere homocedasticidad
wilcox.test(log.species$LRCl~species$SEXO)

#Test multivariados 
#PERMAVOVA
log.species
dmdist.nl<-vegdist(log.species.nl,method = "manhattan")
mad.nl<-adonis(dmdist.nl~sex,data = log.species)
mad.nl
#sin NL
dmdist<-vegdist(log.species,method = "manhattan")
mad<-adonis(dmdist~sex,data = log.species)
mad
#PCA
res.pca <- prcomp(log.species.f, scale. = TRUE)
eig.val <- get_eigenvalue(res.pca)
eig.val
summary(res.pca)
fviz_eig(res.pca)
res.pca$rotation
res.pca <- prcomp(log.species.nl, scale. = TRUE)
eig.val <- get_eigenvalue(res.pca)
eig.val
summary(res.pca)
fviz_eig(res.pca)
res.pca$rotation
#LDA
lda = lda(sex ~  LPr  + LTr +  ANCr , data = log.apollinaris.f, na.action = "na.omit", CV = FALSE)
lda
lda$counts
lda$scaling
p1 = predict(lda, log.apollinaris.f)$class
(tab = table(Predicted = p1, Actual = sex))
p = predict(lda)
freqtable = table(p$class,sex)
sum(diag(tab))/sum(tab) 
data.frame(p$posterior, ObservedGroup = sex, 
           PredictedGroup = p$class, p$x) %>% 
  head(4) %>% 
  pander
matrizlda<-data.frame(p$posterior, ObservedGroup = sex, PredictedGroup = p$class, p$x)
matrizlda<-cbind.data.frame(matrizlda)
log.apollinaris.f$LDA1 = p$x[,1]
#log.apollinaris.f$LDA2 = p$x[,2]
#log.apollinaris.f$LDA3 = p$x[,3]
#log.apollinaris.f$LDA4 = p$x[,4]
#DF = manova(cbind(LDA1) ~ sex, data = log.apollinaris)
#summary(DF)
#summary.aov(DF)
aov<-aov(log.apollinaris.f$LDA1~sex)
summary.aov(aov)

```
```{r}
#PCA
#data
data<-read.csv("mean_values.csv",header = TRUE,sep=";")
#Logarithm transformation 
MT = as.factor((data)[,3])
SP = as.factor((data)[,4])
SVL = as.numeric((data)[,5])
FlL = as.numeric((data)[,7])
HlL = as.numeric((data)[,8])
TrL = as.numeric((data)[,9])
HW = as.numeric((data)[,10])
HH = as.numeric((data)[,11])
HL = as.numeric((data)[,12])
LN = as.numeric((data)[,13])
SVL<-log(SVL)
FlL<-log(FlL)
HlL<-log(HlL)
TrL<-log(TrL)
HW<-log(HW)
HH<-log(HH)
HL<-log(HL)
LN<-log(LN)
#Correción por tamaño
regFlL = lm(SVL ~ FlL) 
regHlL = lm(SVL ~ HlL) 
regTrL = lm(SVL ~ TrL)
regHW = lm(SVL ~ HW)
regHH = lm(SVL ~ HH) 
regHL = lm(SVL ~ HL) 
regLN = lm(SVL ~ LN) 
FlL = regFlL$resid
HlL = regHlL$resid
TrL = regTrL$resid
HW =regHW$resid
HH = regHH$resid
HL = regHL$resid
LN = regLN$resid
names = row.names(data)
log.data = data.frame(cbind(SVL, FlL, HlL, TrL, HW, HH, HL, LN))
res.pca <- prcomp(log.data, scale. = TRUE)
write.csv(res.pca$x,file = "pca_scores.csv")
```
```{r}
#Dimorphism indexes
#SSizeDi
#SSDi manually calculated-> SVLmales/SVLfemales
#SEcoDi
data<-read.csv("pca_scores.csv",header = TRUE,sep = ";")
dmdist<-vegdist(data,method = "manhattan")
mydf<-as.data.frame(as.matrix(dmdist))
write.table(mydf,file = "manhattan_PCA.txt")
#Extract value of distance between males and females
#Is there a way to do it automatically?
```
```{r}
#Is the patern of body size dimorphism, and sex differences in ecomorphological traits explained by averaged body size of the species? 
SSDI_COMPLETE<-read.csv("SSDI_COMPLETE.csv",header = TRUE,sep = ";")
SSDi<-na.omit(SSDI_COMPLETE)
shapiro.test(SSDi$Dim)
shapiro.test(SSDi$Manhattan_PCA)
shapiro.test(SSDi$SIZE)
cor.test(SSDi$SIZE,SSDi$Dim,method = "spearman")
bias<-as.factor(SSDi$BIAS)
mt<-as.factor(SSDi$MT)
plot<-ggplot(SSDi, aes(SIZE, Dim))+  geom_point(aes(shape = BIAS, colour = MT), size = 4, alpha = 0.6) +stat_smooth(method = "lm", col = "dimgray")
plot 
  
plot+geom_vline(xintercept = 60, linetype="dashed", color = "dimgray", size=1)+geom_vline(xintercept = 90, linetype="dashed", color = "dimgray", size=1)+labs(x = "Size (mm)", y = "Size Dimorphism (%)")+geom_hline(yintercept = 5, linetype = "dashed",color = "red",size=1)
ggsave("SizeDimorphism_plot.pdf", 
       dpi = 600, 
       width = 200, height = 150, unit = "mm")
##DImorfismo en forma 
shapiro.test(SSDi$Manhattan_PCA)
shapiro.test(SSDi$SIZE)
cor.test(SSDi$SIZE,SSDi$Manhattan_PCA,method = "spearman")
lm<-lm(formula = SIZE ~ Dim, data = SSDi)
summary.lm(lm)
bias<-as.factor(SSDi$BIAS)
mt<-as.factor(SSDi$MT)
plot<-ggplot(SSDi, aes(SIZE, Manhattan_PCA))+  geom_point(aes(colour = MT), size = 4, alpha = 0.6) +stat_smooth(method = "lm", col = "dimgray")
plot 
  
plot+geom_vline(xintercept = 60, linetype="dashed", color = "dimgray", size=1)+geom_vline(xintercept = 90, linetype="dashed", color = "dimgray", size=1)+labs(x = "Size (mm)", y = "Ecomorphological Dimorphism (Manhattan Distance)")+geom_hline(yintercept = 3.6, linetype = "dashed",color = "red",size=1)
ggsave("SHapeDimorphism_plot.pdf", 
       dpi = 600, 
       width = 200, height = 150, unit = "mm")
```
```{r}
#The degree of sexual dimorphism in body size and shape, and lamellae number differs among morphotypes?
SSDI_COMPLETE <- read.csv("C:/Users/juadr/OneDrive/Escritorio/Documentos trabajo de grado/Anolis_R/SSDI_COMPLETE.csv", sep=";")
data <- SSDI_COMPLETE
aov.ssd<-anova(lm(Dim ~ MT, data = data))
aov.ssd
aov.sed<-anova(lm(Manhattan_PCA ~ MT, data = data))
```
```{r}
#Does the inclusion of sex variation modify the previous morphotype assignment of species?
#LDA new classification 
data<-read.csv("cluster_groups.csv",header = TRUE,sep = ";")
data<-data[c(-7,-8,-9,-10)]
data<-textshape::column_to_rownames(data, loc = 1)
data
#DFA
lda = lda(Group_lda_2 ~  SVL+ FlL  +  TL + LN , data = data, na.action = "na.omit", CV = FALSE)
lda
#No especies por grupo 
lda$counts
#COntribución de cada variable por función
lda$scaling
p1 = predict(lda, data)$class
(tab = table(Predicted = p1, Actual = data$Group_lda_1))
#  matriz de prediccion
p = predict(lda)
freqtable = table(p$class, data$Group_lda_1)
#matriz de exactitud
sum(diag(tab))/sum(tab) 
#Función discriminante obs v PRed por sp
data.frame(p$posterior, ObservedGroup = data$Group_lda_2, 
           PredictedGroup = p$class, p$x) %>% 
  head(4) %>% 
  pander

lda_2_matrix<-data.frame(p$posterior, ObservedGroup = data$Group_lda_2, PredictedGroup = p$class, p$x)
lda_2_matrix<-cbind.data.frame(lda_2_matrix,row.names(data))
write.table(lda_2_matrix,file = "lda_2_matrix.txt")
#Extraemos los valores de cada funcion para cada especie
data$LDA1 = p$x[,1]
data$LDA2 = p$x[,2]
data$LDA3 = p$x[,3]
data$LDA4 = p$x[,4]

write.table(data,file = "lda_scores.txt")
# hacemos un grafico de densidad para cada funcion
#cambio tabla de txt a csv
data<-read.csv("lda_scores.csv",sep = ";")
data<-textshape::column_to_rownames(data, loc = 1)
ggplot(data, aes(LDA1, fill= lda_2_matrix$PredictedGroup)) + 
  geom_density(alpha = 0.5, color = NA) + 
  theme(legend.position = "top")
#Visualizar

gMeans = data %>% group_by(MT) %>% select(LDA1, LDA2) %>% 
  summarise_each(funs(mean)) 
#Grafica 

gMeans %>% pander
plot(lda, col = as.integer(MT)) # Grafica todos las funciones
ggplot(data, aes(LDA1, LDA2, color =MT)) + 
  geom_point(alpha = 0) + 
  geom_text(data = gMeans, 
            aes(label = MT),
            color = "black", 
            vjust = 1.75) + 
  geom_point(data = gMeans, 
             aes(fill =MT), 
             size = 4, 
             color = "black", 
             pch = 21) + 
  theme(legend.position = "down") +
  coord_equal() + theme_bw() + 
  labs(x = "DF1 = 72.73%", y = "DF2 = 22.39%") +
  theme(plot.title = element_text(hjust = 0.5))
ggsave("lda_2.pdf", 
       dpi = 600, 
       width = 200, height = 150, unit = "mm")
```
```{r}
#How much is sexual dimorphism contributing to overall morphological diversity of these species?
data <- read.csv("groups.txt", header=T)
attach(data)
unit=1.0
min1 <- floor(min(can1))
min2 <- floor(min(can2))
min3 <- floor(min(can3))
max1 <- ceiling(max(can1))
max2 <- ceiling(max(can2))
max3 <- ceiling(max(can3))

r1 <- seq(min1, max1, by=unit)
r2 <- seq(min2, max2, by=unit)
r3 <- seq(min3, max3, by=unit)
#escalamiento multidimensional 
#PCOA

cut(s0$can1, br=r1, labels=FALSE ) -> bin1
cut(s0$can2, br=r2, labels=FALSE ) -> bin2
cut(s0$can3, br=r3, labels=FALSE ) -> bin3

nrows <- max(bin1)
ncols <- max(bin2) 

index <- bin1 + (bin2-1)*nrows + (bin3-1)*(nrows*ncols)
length(unique(index)) -> ncubesall			
length(unique(index[sex=="F"])) -> ncubesFobs  
length(unique(index[sex=="M"])) -> ncubesMobs  
obsscore <- ncubesall - ncubesMobs
```
```{r}
#Is the pattern of sexual dimorphism explained by the comunity species composition?
#QUestion pending


```

