---
title: "R Notebook"
output: html_notebook
---
```{r}
#Learning how to Use SURFACE"
library(surface)
tree<-surfaceDemo$tree
dat<-surfaceDemo$sim$dat
tree
tree<-nameNodes(tree)
olist<-convertTreeData(tree,dat)
otree<-olist[[1]]; odata<-olist[[2]]
fwd<-surfaceForward(otree, odata, aic_threshold = 0, exclude = 0,verbose = FALSE, plotaic = FALSE)
k<-length(fwd)
fsum<-surfaceSummary(fwd)
names(fsum)
fsum$aics
bwd<-surfaceBackward(otree, odata, starting_model = fwd[[k]], aic_threshold = 0,only_best = TRUE, verbose = FALSE, plotaic = FALSE)
bsum<-surfaceSummary(bwd)
kk<-length(bwd)
bsum$alpha
bsum$sigma_squared
bsum$theta
bsum$n_regimes
surfaceTreePlot(tree, bwd[[kk]], labelshifts = T)
oldpar <- par(no.readonly = TRUE)
par(mfrow=c(1,2), mai=c(0.8,0.8,0.2,0.2))
surfaceTraitPlot(dat, bwd[[kk]], whattraits = c(1,2))
surfaceTraitPlot(dat, bwd[[kk]], whattraits = c(3,2))
par(oldpar)
bm<-startingModel(otree,odata,brownian=TRUE)
ou1<-startingModel(otree,odata)
H12<-startingModel(otree,odata,shifts=c("26"="H1","13"="H1","5"="H2","19"="H2"))
surfaceAICPlot(fwd, bwd)
abline(h=bm[[1]]$aic,lty="longdash")
abline(h=H12[[1]]$aic,lty="longdash")
text(c(6,6),c(bm[[1]]$aic, ou1[[1]]$aic, H12[[1]]$aic)-2,c("BM","OU1","H12"),cex=0.5)
truefit<-surfaceDemo$sim$fit
propRegMatch(truefit, bwd[[kk]]$fit, internal = FALSE)
propRegMatch(truefit, bwd[[kk]]$fit, internal = TRUE)
set.seed(10)
newsim<-surfaceSimulate(tree, type="hansen-fit", hansenfit=fwd[[k]]$fit, shifts=fwd[[k]]$savedshifts, sample_optima=TRUE)
oldpar <- par(no.readonly = TRUE)
par(mfrow=c(1,2),mai=c(0.8,0.8,0.2,0.2))
surfaceTraitPlot(newsim$data, newsim, whattraits = c(1,2), convcol = FALSE)
surfaceTraitPlot(newsim$data, newsim, whattraits = c(3,2), convcol = FALSE)
par(oldpar)
newout<-runSurface(tree, newsim$dat, only_best = TRUE)
newsum<-surfaceSummary(newout$bwd)
newkk<-length(newout$bwd)
newsum$n_regimes
bsum$n_regimes
oldpar <- par(no.readonly = TRUE)
par(mfrow=c(1,2),mai=c(0.8,0.8,0.2,0.2))
surfaceTraitPlot(newsim$data, newout$bwd[[newkk]], whattraits = c(1,2))
surfaceTraitPlot(newsim$data, newout$bwd[[newkk]], whattraits = c(3,2))
par(oldpar)

```
```{r}
# MCC Anole tree from Poe et al. 2017 
SSDI_COMPLETE <- read.csv("C:/Users/juadr/OneDrive/Escritorio/Documentos trabajo de grado/Anolis_R/SSDI_COMPLETE.csv", sep=";")

Dactyloa<-subset(SSDI_COMPLETE,CLADE=="Dactyloa")
Draconura<-subset(SSDI_COMPLETE,CLADE=="Draconura")
tree = read.nexus("MCCtree.tre")
is.ultrametric(tree)
force.ultrametric = function(tree,method=c("nnls","extend")){
  method = method[1]
  if(method=="nnls") tree = nnls.tree(cophenetic(tree),tree,
                                     rooted=TRUE,trace=0)
  else if(method=="extend"){
    h=diag(vcv(tree))
    d=max(h)-h
    ii=sapply(1:Ntip(tree),function(x,y) which(y==x),
               y=tree$edge[,2])
    tree$edge.length[ii]=tree$edge.length[ii]+d
  } else 
    cat("method not recognized: returning input tree\n\n")
  tree
}
tree = force.ultrametric(tree,method="nnls")
write.nexus(tree,file = "arbol.nex")
tree$tip.label
is.ultrametric(tree)
species.dactyloa=Dactyloa$SP
species.dactyloa = c("anchicayae","apollinaris","calimae","chloris", "purpurescens","danieli","aequatorialis","eulaemus","fasciatus","fraseri","gorgonae","heterodermus","huilae","latifrons","maculigula","megalopithecus","mirus","nicefori","peraccae","princeps","ruizii","solitarius","transversalis","umbrivagus","vaupesianus","ventrimaculatus")
species.draconura=Draconura$SP

pruned.tree.dactyloa = drop.tip(tree,tree$tip.label[-match(species.dactyloa, tree$tip.label)])

pruned.tree.draconura = drop.tip(tree,tree$tip.label[-match(species.draconura, tree$tip.label)])
Dactyloa<-textshape::column_to_rownames(Dactyloa, loc = 2)
Draconura<-textshape::column_to_rownames(Draconura, loc = 2)
plot(pruned.tree.dactyloa)
plot(pruned.tree.draconura)
obj<-name.check(pruned.tree.dactyloa,Dactyloa)
obj
obj<-name.check(pruned.tree.draconura,Draconura)
obj
plotTree(tree)
total.species<-c(species.dactyloa,species.draconura)
pruned.tree = drop.tip(tree,tree$tip.label[-match(total.species, tree$tip.label)])
plotTree(pruned.tree)
tree<-pruned.tree
```
```{r}
data <- read.csv("C:/Users/juadr/OneDrive/Escritorio/Documentos trabajo de grado/Anolis_R/0_promedios.csv", sep=";")
data<-data[c(-5)]
data<-na.omit(data)
##machos
data<-subset(data,SEXO=="M")
#transform
SP = as.factor((data)[,3])
SVL = as.numeric((data)[,4])
FlL = as.numeric((data)[,5])
HlL = as.numeric((data)[,6])
TrL = as.numeric((data)[,7])
HW = as.numeric((data)[,8])
HH = as.numeric((data)[,9])
HL = as.numeric((data)[,10])
LN = as.numeric((data)[,11])
SVL<-log(SVL)
FlL<-log(FlL)
HlL<-log(HlL)
TrL<-log(TrL)
HW<-log(HW)
HH<-log(HH)
HL<-log(HL)
LN<-log(LN)
#Correci칩n por tama침o
regFlL = lm(SVL ~ FlL) 
regHlL = lm(SVL ~ HlL) 
regTrL = lm(SVL ~ TrL)
regHW = lm(SVL ~ HW)
regHH = lm(SVL ~ HH) 
regHL = lm(SVL ~ HL) 
regLN = lm(SVL ~ LN) 
FlL = regFlL$resid
HlL = regHlL$resid
TrL = regTrL$resid
HW =regHW$resid
HH = regHH$resid
HL = regHL$resid
LN = regLN$resid
names = row.names(data)
log.data.m = data.frame(cbind(SVL, FlL, HlL, TrL, HW, HH, HL, LN),row.names = SP)
#FEMALES
data <- read.csv("C:/Users/juadr/OneDrive/Escritorio/Documentos trabajo de grado/Anolis_R/0_promedios.csv", sep=";")
data<-data[c(-5)]
data<-na.omit(data)
##machos
data<-subset(data,SEXO=="F")
#transform
SP = as.factor((data)[,3])
SVL = as.numeric((data)[,4])
FlL = as.numeric((data)[,5])
HlL = as.numeric((data)[,6])
TrL = as.numeric((data)[,7])
HW = as.numeric((data)[,8])
HH = as.numeric((data)[,9])
HL = as.numeric((data)[,10])
LN = as.numeric((data)[,11])
SVL<-log(SVL)
FlL<-log(FlL)
HlL<-log(HlL)
TrL<-log(TrL)
HW<-log(HW)
HH<-log(HH)
HL<-log(HL)
LN<-log(LN)
#Correci칩n por tama침o
regFlL = lm(SVL ~ FlL) 
regHlL = lm(SVL ~ HlL) 
regTrL = lm(SVL ~ TrL)
regHW = lm(SVL ~ HW)
regHH = lm(SVL ~ HH) 
regHL = lm(SVL ~ HL) 
regLN = lm(SVL ~ LN) 
FlL = regFlL$resid
HlL = regHlL$resid
TrL = regTrL$resid
HW =regHW$resid
HH = regHH$resid
HL = regHL$resid
LN = regLN$resid
names = row.names(data)
log.data.f = data.frame(cbind(SVL, FlL, HlL, TrL, HW, HH, HL, LN),row.names = SP)
```
```{r}
#SURFACE_MALES
dat<-log.data.m
tree<-pruned.tree
tree<-nameNodes(tree)
olist<-convertTreeData(tree,dat)
otree<-olist[[1]]; odata<-olist[[2]]
fwd<-surfaceForward(otree, odata, aic_threshold = 0, exclude = 0,verbose = FALSE, plotaic = FALSE)
k<-length(fwd)
fsum<-surfaceSummary(fwd)
names(fsum)
fsum$aics
bwd<-surfaceBackward(otree, odata, starting_model = fwd[[k]], aic_threshold = 0,only_best = TRUE, verbose = FALSE, plotaic = FALSE)
bsum<-surfaceSummary(bwd)
kk<-length(bwd)
bsum$alpha
bsum$sigma_squared
bsum$theta
bsum$n_regimes
surfaceTreePlot(tree, bwd[[kk]], labelshifts = T)
oldpar <- par(no.readonly = TRUE)
par(mfrow=c(1,2), mai=c(0.8,0.8,0.2,0.2))
surfaceTraitPlot(dat, bwd[[kk]], whattraits = c(1,2))
surfaceTraitPlot(dat, bwd[[kk]], whattraits = c(3,2))
par(oldpar)
bm<-startingModel(otree,odata,brownian=TRUE)
ou1<-startingModel(otree,odata)
H12<-startingModel(otree,odata,shifts=c("26"="H1","13"="H1","5"="H2","19"="H2"))
surfaceAICPlot(fwd, bwd)
abline(h=bm[[1]]$aic,lty="longdash")
abline(h=H12[[1]]$aic,lty="longdash")
text(c(6,6),c(bm[[1]]$aic, ou1[[1]]$aic, H12[[1]]$aic)-2,c("BM","OU1","H12"),cex=0.5)
truefit<-surfaceDemo$sim$fit
propRegMatch(truefit, bwd[[kk]]$fit, internal = FALSE)
propRegMatch(truefit, bwd[[kk]]$fit, internal = TRUE)
set.seed(10)
newsim<-surfaceSimulate(tree, type="hansen-fit", hansenfit=fwd[[k]]$fit, shifts=fwd[[k]]$savedshifts, sample_optima=TRUE)
oldpar <- par(no.readonly = TRUE)
par(mfrow=c(1,2),mai=c(0.8,0.8,0.2,0.2))
surfaceTraitPlot(newsim$data, newsim, whattraits = c(1,2), convcol = FALSE)
surfaceTraitPlot(newsim$data, newsim, whattraits = c(3,2), convcol = FALSE)
par(oldpar)
newout<-runSurface(tree, newsim$dat, only_best = TRUE)
newsum<-surfaceSummary(newout$bwd)
newkk<-length(newout$bwd)
newsum$n_regimes
bsum$n_regimes
oldpar <- par(no.readonly = TRUE)
par(mfrow=c(1,2),mai=c(0.8,0.8,0.2,0.2))
surfaceTraitPlot(newsim$data, newout$bwd[[newkk]], whattraits = c(1,2))
surfaceTraitPlot(newsim$data, newout$bwd[[newkk]], whattraits = c(3,2))
par(oldpar)
#SURFACE_FEMALES
#SURFACE_MALES
dat<-log.data.f
tree<-pruned.tree
tree<-nameNodes(tree)
olist<-convertTreeData(tree,dat)
otree<-olist[[1]]; odata<-olist[[2]]
fwd<-surfaceForward(otree, odata, aic_threshold = 0, exclude = 0,verbose = FALSE, plotaic = FALSE)
k<-length(fwd)
fsum<-surfaceSummary(fwd)
names(fsum)
fsum$aics
bwd<-surfaceBackward(otree, odata, starting_model = fwd[[k]], aic_threshold = 0,only_best = TRUE, verbose = FALSE, plotaic = FALSE)
bsum<-surfaceSummary(bwd)
kk<-length(bwd)
bsum$alpha
bsum$sigma_squared
bsum$theta
bsum$n_regimes
surfaceTreePlot(tree, bwd[[kk]], labelshifts = T)
oldpar <- par(no.readonly = TRUE)
par(mfrow=c(1,2), mai=c(0.8,0.8,0.2,0.2))
surfaceTraitPlot(dat, bwd[[kk]], whattraits = c(1,2))
surfaceTraitPlot(dat, bwd[[kk]], whattraits = c(3,2))
par(oldpar)
bm<-startingModel(otree,odata,brownian=TRUE)
ou1<-startingModel(otree,odata)
H12<-startingModel(otree,odata,shifts=c("26"="H1","13"="H1","5"="H2","19"="H2"))
surfaceAICPlot(fwd, bwd)
abline(h=bm[[1]]$aic,lty="longdash")
abline(h=H12[[1]]$aic,lty="longdash")
text(c(6,6),c(bm[[1]]$aic, ou1[[1]]$aic, H12[[1]]$aic)-2,c("BM","OU1","H12"),cex=0.5)
truefit<-surfaceDemo$sim$fit
propRegMatch(truefit, bwd[[kk]]$fit, internal = FALSE)
propRegMatch(truefit, bwd[[kk]]$fit, internal = TRUE)
set.seed(10)
newsim<-surfaceSimulate(tree, type="hansen-fit", hansenfit=fwd[[k]]$fit, shifts=fwd[[k]]$savedshifts, sample_optima=TRUE)
oldpar <- par(no.readonly = TRUE)
par(mfrow=c(1,2),mai=c(0.8,0.8,0.2,0.2))
surfaceTraitPlot(newsim$data, newsim, whattraits = c(1,2), convcol = FALSE)
surfaceTraitPlot(newsim$data, newsim, whattraits = c(3,2), convcol = FALSE)
par(oldpar)
newout<-runSurface(tree, newsim$dat, only_best = TRUE)
newsum<-surfaceSummary(newout$bwd)
newkk<-length(newout$bwd)
newsum$n_regimes
bsum$n_regimes
oldpar <- par(no.readonly = TRUE)
par(mfrow=c(1,2),mai=c(0.8,0.8,0.2,0.2))
surfaceTraitPlot(newsim$data, newout$bwd[[newkk]], whattraits = c(1,2))
surfaceTraitPlot(newsim$data, newout$bwd[[newkk]], whattraits = c(3,2))
par(oldpar)
```



